[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30315
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = true

[rpc]
port = 8647
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts","signer"]
interface = "all"
cors = ["all"]

[websockets]
disable = false
port = 10646
interface = "all"
origins = ["none"]
apis = ["all"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x4e42a7d90b861fce9c12808055ccffbfaa6d3920"  
gas_floor_target = "40000000"
reseal_on_txs = "none" 
usd_per_tx = "0" 
force_sealing = true
refuse_service_transactions = false

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true